[package]
name = "xelarius-node"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
libp2p = "0.53"
serde_json = "1.0"
xelarius-core = { path = "../xelarius-core" }
