[package]
name = "xelarius-core"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
sled = "0.34"
bincode = "1.3"
wasmtime = "14.0"
anyhow = "1.0"
prometheus = "0.14"
lazy_static = "1.4"